# Generated by Django 4.0.1 on 2022-02-18 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_vote', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email_address', models.EmailField(max_length=254)),
                ('Phone_No', models.IntegerField()),
                ('Address', models.TextField(max_length=200)),
                ('Electoral', models.ImageField(upload_to='')),
                ('Votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='Address',
            field=models.TextField(max_length=200),
        ),
    ]
